name: scale-workshop

services:
  scale-workshop_dev:
    build:
      context: .
      args:
        USER: ${USER:-dev}
        UID: ${UID:-1000}
        USER_PASSWORD: ${USER_PASSWORD:-12345678}
        GITHUB_EMAIL: ${GITHUB_EMAIL}
        SSH_PASSWORD: ${SSH_PASSWORD}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
        GIT_USER_NAME: ${GIT_USER_NAME}
      dockerfile: ./Dockerfile
    #entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["zsh", "-c", "echo Container started; tail -f /dev/null"]
    env_file:
      - .env
    environment:
      SSH_KEY_PATH: /home/${USER:-dev}/.ssh/github
      SSH_PASSWORD: ${SSH_PASSWORD:-12345678}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
    image: scale-workshop_dev:latest
    container_name: scale-workshop_dev
    tty: true
    volumes:
      - ../../:/var/www/scale-workshop
      - ./config/.zshrc:/home/${USER:-dev}/.zshrc
      - ./config/.p10k.zsh:/home/${USER:-dev}/.p10k.zsh
      - ./config/starship.toml:/home/${USER:-dev}/.config/starship.toml
      - ./config/neovim_distros:/home/${USER:-dev}/.config/nvims/neovim_distros
    working_dir: /var/www/scale-workshop
    ports:
      - "5173:5173"
    networks:
      - scale-workshop

networks:
  scale-workshop:
    name: scale-workshop
    driver: bridge
